(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='last10seconds-save-v1';
const DEFAULT={bestScore:0,highestLevel:1,coins:0,highestCombo:0,runs:0,successes:0,failures:0,totalScore:0,totalCoins:0,totalTime:0,categories:{},challengeWins:{},daily:{date:'',complete:false,best:0},settings:{sound:true,vibration:true,reducedMotion:false},achievements:[],cosmetic:'mint'};
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return merge(clone(DEFAULT),x&&typeof x==='object'?x:{})}catch(e){return clone(DEFAULT)}}
function merge(a,b){Object.keys(a).forEach(k=>{if(b[k]!==undefined)a[k]=a[k]&&typeof a[k]==='object'&&!Array.isArray(a[k])?merge(a[k],b[k]):b[k]});return a}
let state=load();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){return false}}
const app=$('#app'), announce=$('#announce');
let screen='menu',game=null,audio=null;
const colors=['red','green','blue','yellow','violet'];
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dateKey(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function seeded(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function unlockAudio(){if(!state.settings.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}catch(e){}}
function beep(ok=true){if(!state.settings.sound)return;unlockAudio();if(!audio)return;try{const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=ok?640:130;g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.13)}catch(e){}}
function buzz(p){if(state.settings.vibration&&navigator.vibrate)try{navigator.vibrate(p)}catch(e){}}
document.addEventListener('pointerdown',unlockAudio,{once:true});
function top(title='LAST 10 SECONDS'){return `<div class="top"><div class="logo">${title.replace('10','<span>10</span>')}</div>${screen!=='menu'?'<button class="icon" data-go="menu" aria-label="Back to main menu">←</button>':'<span></span>'}</div>`}
function renderMenu(){screen='menu';game&&game.destroy();game=null;app.innerHTML=`<section class="screen">${top()}<div class="hero"><div class="kicker">TEN SECONDS. ONE CHANCE.</div><h1>LAST <em>10</em><br>SECONDS</h1><p>Rapid-fire tests of speed, memory, accuracy, logic and nerve. One wrong move ends the run.</p></div><div class="stat-grid"><div class="stat"><small>BEST SCORE</small><b>${state.bestScore}</b></div><div class="stat"><small>TOP LEVEL</small><b>${state.highestLevel}/20</b></div><div class="stat"><small>COINS</small><b>◆ ${state.coins}</b></div></div><div class="actions main"><button class="btn primary" data-play="normal">▶ PLAY</button><button class="btn daily" data-go="daily">☀ DAILY</button></div><div class="nav-grid"><button class="btn" data-go="stats">▥ Stats</button><button class="btn" data-go="achievements">★ Awards</button><button class="btn" data-go="settings">⚙ Settings</button><button class="btn" data-go="how">? How to play</button></div><p class="footer-note">30 challenges · 20 difficulty levels · progress saved locally</p></section>`;bindNav()}
function bindNav(){$$('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));$$('[data-play]').forEach(b=>b.onclick=()=>startGame(b.dataset.play))}
function navigate(to){if(to==='menu')return renderMenu();if(to==='daily')return renderDaily();if(to==='stats')return renderStats();if(to==='achievements')return renderAchievements();if(to==='settings')return renderSettings();if(to==='how')return renderHow()}
function renderDaily(){screen='daily';const d=dateKey(),same=state.daily.date===d;app.innerHTML=`<section class="screen">${top('DAILY 10')}<h1 class="page-title">Today's sequence</h1><p class="subtitle">Everyone gets the same deterministic 10-challenge order for ${d}. Challenge choices and content use a date-seeded generator.</p><div class="card"><div class="stat-grid"><div class="stat"><small>STATUS</small><b>${same&&state.daily.complete?'Complete':'Ready'}</b></div><div class="stat"><small>BEST</small><b>${same?state.daily.best:0}</b></div><div class="stat"><small>LENGTH</small><b>10</b></div></div><button class="btn primary" data-play="daily">${same&&state.daily.complete?'REPLAY DAILY':'START DAILY'}</button></div></section>`;bindNav()}
const ACH=[
['first','First Breath','Complete one challenge',s=>s.successes>=1],['five','Getting Warm','Complete 5 challenges',s=>s.successes>=5],['fifty','Focused','Complete 50 challenges',s=>s.successes>=50],['century','Centurion','Complete 100 challenges',s=>s.successes>=100],['combo3','Hat Trick','Reach a 3 combo',s=>s.highestCombo>=3],['combo5','On Fire','Reach a 5 combo',s=>s.highestCombo>=5],['combo10','Untouchable','Reach a 10 combo',s=>s.highestCombo>=10],['level5','Level Up','Reach level 5',s=>s.highestLevel>=5],['level10','Halfway','Reach level 10',s=>s.highestLevel>=10],['level20','Last Level','Reach level 20',s=>s.highestLevel>=20],['score500','Quick 500','Score 500 in one run',s=>s.bestScore>=500],['score2000','Two Grand','Score 2,000 in one run',s=>s.bestScore>=2000],['score5000','Arcade Royalty','Score 5,000 in one run',s=>s.bestScore>=5000],['runs5','Persistent','Play 5 runs',s=>s.runs>=5],['runs25','Regular','Play 25 runs',s=>s.runs>=25],['coins100','Pocket Change','Earn 100 total coins',s=>s.totalCoins>=100],['coins500','Treasure','Earn 500 total coins',s=>s.totalCoins>=500],['daily','Today Matters','Complete a daily sequence',s=>s.daily.complete],['speed','Speed Specialist','Win 10 Speed challenges',s=>(s.categories.Speed||0)>=10],['memory','Memory Specialist','Win 10 Memory challenges',s=>(s.categories.Memory||0)>=10],['accuracy','Accuracy Specialist','Win 10 Accuracy challenges',s=>(s.categories.Accuracy||0)>=10],['logic','Logic Specialist','Win 10 Logic challenges',s=>(s.categories.Logic||0)>=10],['reaction','Reaction Specialist','Win 10 Reaction challenges',s=>(s.categories.Reaction||0)>=10],['trick','Trickster','Win 10 Trick challenges',s=>(s.categories.Trick||0)>=10]
];
function checkAchievements(){const fresh=[];ACH.forEach(a=>{if(!state.achievements.includes(a[0])&&a[3](state)){state.achievements.push(a[0]);state.coins+=10;state.totalCoins+=10;fresh.push(a[1])}});save();return fresh}
function renderAchievements(){screen='achievements';checkAchievements();app.innerHTML=`<section class="screen">${top('ACHIEVEMENTS')}<h1 class="page-title">Achievements</h1><p class="subtitle">${state.achievements.length} of ${ACH.length} unlocked · each awards ◆ 10</p><div class="list">${ACH.map((a,i)=>{const on=state.achievements.includes(a[0]);return `<div class="card achievement ${on?'':'locked'}"><div class="badge">${on?'★':'◈'}</div><div><b>${esc(a[1])}</b><p>${esc(a[2])}</p></div><strong>${on?'UNLOCKED':'LOCKED'}</strong></div>`}).join('')}</div></section>`;bindNav()}
const COS=[['mint','Mint Pulse',0],['violet','Violet Rush',100],['gold','Golden Hour',250],['rose','Rose Alert',500],['blue','Blue Shift',750],['mono','Monochrome',1200]];
function renderStats(){screen='stats';const rate=state.successes+state.failures?Math.round(state.successes/(state.successes+state.failures)*100):0;app.innerHTML=`<section class="screen">${top('STATISTICS')}<h1 class="page-title">Your record</h1><div class="stat-grid"><div class="stat"><small>RUNS</small><b>${state.runs}</b></div><div class="stat"><small>SUCCESSES</small><b>${state.successes}</b></div><div class="stat"><small>WIN RATE</small><b>${rate}%</b></div><div class="stat"><small>BEST</small><b>${state.bestScore}</b></div><div class="stat"><small>TOP COMBO</small><b>x${state.highestCombo}</b></div><div class="stat"><small>TOTAL SCORE</small><b>${state.totalScore}</b></div></div><h2>Category wins</h2><div class="card">${['Speed','Memory','Accuracy','Logic','Reaction','Trick'].map(x=>`<div class="setting"><span>${x}</span><b>${state.categories[x]||0}</b></div>`).join('')}</div><h2>Cosmetic pulse</h2><p class="subtitle">Cosmetics unlock from total coins earned and never affect gameplay.</p><div class="cosmetics">${COS.map(c=>`<button class="cosmetic ${state.cosmetic===c[0]?'selected':''}" data-cos="${c[0]}" ${state.totalCoins<c[2]?'disabled':''}>${c[1]}<br><small>${state.totalCoins>=c[2]?'Select':`◆ ${c[2]} earned`}</small></button>`).join('')}</div></section>`;bindNav();$$('[data-cos]').forEach(b=>b.onclick=()=>{state.cosmetic=b.dataset.cos;save();applyCosmetic();renderStats()})}
function applyCosmetic(){const map={mint:['#63f3d0','#ffcf4a'],violet:['#ad8cff','#68e7ff'],gold:['#ffd65a','#ff875c'],rose:['#ff6fae','#77f4db'],blue:['#55b8ff','#b0ff75'],mono:['#fff','#aeb5c8']},c=map[state.cosmetic]||map.mint;document.documentElement.style.setProperty('--accent',c[0]);document.documentElement.style.setProperty('--accent2',c[1]);document.body.classList.toggle('reduce-motion',state.settings.reducedMotion)}
function renderSettings(){screen='settings';app.innerHTML=`<section class="screen">${top('SETTINGS')}<h1 class="page-title">Settings</h1><div class="list">${[['sound','Sound','Light Web Audio cues'],['vibration','Vibration','Haptic feedback when supported'],['reducedMotion','Reduced motion','Minimize animation and movement']].map(x=>`<div class="card setting"><div><b>${x[1]}</b><div class="subtitle">${x[2]}</div></div><button class="toggle ${state.settings[x[0]]?'on':''}" data-set="${x[0]}" role="switch" aria-checked="${state.settings[x[0]]}" aria-label="Toggle ${x[1]}"></button></div>`).join('')}</div><h2>Progress</h2><button class="btn danger" id="reset">Reset all progress</button></section>`;bindNav();$$('[data-set]').forEach(b=>b.onclick=()=>{state.settings[b.dataset.set]=!state.settings[b.dataset.set];save();applyCosmetic();renderSettings()});$('#reset').onclick=()=>{if(confirm('Reset scores, coins, achievements, stats and settings? This cannot be undone.')){state=clone(DEFAULT);save();applyCosmetic();renderMenu()}}}
function renderHow(){screen='how';app.innerHTML=`<section class="screen how">${top('HOW TO PLAY')}<h1 class="page-title">Ten seconds. Go.</h1><div class="card"><ol><li>Read the instruction, then act before the timer reaches zero.</li><li>A wrong tap, wrong answer or timeout ends the run immediately.</li><li>Every success raises your combo and difficulty. Level increases every two wins, up to 20.</li><li>Score = round((100 × challenge) × level multiplier + time bonus) × combo multiplier.</li><li>Combo multipliers: 1=x1, 2=x1.2, 3=x1.5, 4=x2, 5+=x3.</li></ol><div class="formula">BASE 100 × challenge multiplier<br>DIFFICULTY × (1 + (level−1) × 0.06)<br>TIME BONUS + remaining seconds × 8<br>THEN × combo multiplier</div><p>Keyboard: Tab/Enter activate controls. Number keys select visible choices. Escape pauses a run.</p></div></section>`;bindNav()}
class Scheduler{constructor(){this.items=[];this.paused=false}timeout(fn,ms){const x={fn,left:ms,start:performance.now(),id:0};x.id=setTimeout(()=>{this.items=this.items.filter(i=>i!==x);fn()},ms);this.items.push(x);return x}interval(fn,ms){const loop=()=>{fn();if(this.items.includes(x))x.t=this.timeout(loop,ms)};const x={t:null};this.items.push(x);x.t=this.timeout(loop,ms);return x}raf(fn){let id;const loop=t=>{if(!this.paused)fn(t);id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);const x={raf:()=>cancelAnimationFrame(id)};this.items.push(x);return x}listen(el,type,fn,opt){el.addEventListener(type,fn,opt);this.items.push({off:()=>el.removeEventListener(type,fn,opt)})}pause(){this.paused=true;const n=performance.now();this.items.forEach(x=>{if(x.fn&&x.id){clearTimeout(x.id);x.left-=n-x.start;x.id=0}})}resume(){this.paused=false;this.items.forEach(x=>{if(x.fn&&!x.id){x.start=performance.now();x.id=setTimeout(()=>{this.items=this.items.filter(i=>i!==x);x.fn()},Math.max(0,x.left))}})}clear(){this.items.forEach(x=>{if(x.id)clearTimeout(x.id);if(x.off)x.off();if(x.raf)x.raf();if(x.t&&x.t.id)clearTimeout(x.t.id)});this.items=[]}}
class ChallengeManager{constructor(owner){this.owner=owner;this.scheduler=new Scheduler();this.current=null;this.token=0}start(def){this.cleanup();this.current=def;this.token++;const token=this.token,control={success:()=>token===this.token&&this.owner.succeed(),failure:m=>token===this.token&&this.owner.fail(m),scheduler:this.scheduler,rng:()=>this.owner.rand(),level:this.owner.level,arena:$('#arena')};return def.setup(control)}cleanup(){this.token++;this.scheduler.clear();if(this.current)try{this.current.cleanup()}catch(e){}this.current=null}pause(){this.scheduler.pause()}resume(){this.scheduler.resume()}}
const meta=[
['tap-rush','Tap Rush','Speed',1,10,1],['tap-sequence','Number Chase','Speed',1,10,1.1],['moving-target','Moving Target','Speed',2,10,1.2],['double-tap','Double Tap','Speed',2,8,1],['press-hold','Hold Steady','Speed',3,8,1.2],
['remember-number','Number Memory','Memory',1,10,1.1],['color-sequence','Color Sequence','Memory',3,10,1.3],['position-memory','Position Memory','Memory',4,10,1.3],['word-memory','Word Memory','Memory',5,10,1.2],['flash-count','Flash Counter','Memory',6,10,1.3],
['tiny-target','Precision Tap','Accuracy',1,10,1.2],['stop-bar','Stop the Bar','Accuracy',2,10,1.2],['center-hit','Bullseye','Accuracy',4,10,1.3],['smallest','Pick Smallest','Accuracy',3,10,1.1],['largest','Pick Largest','Accuracy',3,10,1.1],
['arithmetic','Quick Math','Logic',1,10,1.1],['number-sequence','Next Number','Logic',3,10,1.2],['odd-symbol','Odd One Out','Logic',2,10,1.1],['sort-numbers','Sort It','Logic',5,10,1.3],['parity','Odd or Even','Logic',2,8,1],
['wait-signal','Wait for Green','Reaction',1,8,1.2],['signal-choice','Signal Choice','Reaction',4,8,1.3],['falling-catch','Catch It','Reaction',5,10,1.3],['key-flash','Key Flash','Reaction',3,8,1.2],['color-change','Color Change','Reaction',6,8,1.3],
['except','Tap Except','Trick',2,10,1.3],['stroop','Stroop Test','Trick',4,10,1.3],['reverse','Reverse Order','Trick',5,10,1.4],['dont-tap','Do Not Tap','Trick',3,5,1.4],['fake-button','Real Button','Trick',7,10,1.4]
];
function instruction(id,g){const n=Math.min(12,4+Math.floor(g.level/3));return ({'tap-rush':`Tap the button ${n} times`,'tap-sequence':'Tap numbers in ascending order','moving-target':'Catch the moving target','double-tap':'Double-tap the target','press-hold':'Press and hold until complete','remember-number':'Memorize the number','color-sequence':'Repeat the color sequence','position-memory':'Remember the highlighted tiles','word-memory':'Remember the word','flash-count':'Count the flashes','tiny-target':'Tap the small target','stop-bar':'Stop inside the green zone','center-hit':'Tap the center of the bullseye','smallest':'Tap the smallest shape','largest':'Tap the largest shape','arithmetic':'Solve the equation','number-sequence':'Choose the next number','odd-symbol':'Find the different symbol','sort-numbers':'Tap numbers low to high','parity':'Is the number odd or even?','wait-signal':'Wait for green, then tap','signal-choice':'Tap the matching signal','falling-catch':'Catch the falling target','key-flash':'Press the shown key','color-change':'Tap when the panel changes','except':'Tap everything except the forbidden symbol','stroop':'Choose the INK color, not the word','reverse':'Tap numbers in descending order','dont-tap':'Do not tap anything','fake-button':'Tap the only REAL button'})[id]}
const challenges=meta.map(m=>({id:m[0],name:m[1],category:m[2],minimumLevel:m[3],timeLimit:m[4],scoreMultiplier:m[5],instructionGenerator:g=>instruction(m[0],g),setup:c=>setupChallenge(m[0],c),cleanup:()=>{}}));
window.ChallengeManager=ChallengeManager;window.LAST10_CHALLENGES=challenges;
function btnGrid(c,items,correct,labels=items){c.arena.className='arena grid';c.arena.innerHTML=`<div class="choice-grid">${items.map((x,i)=>`<button class="choice" data-v="${esc(x)}">${esc(labels[i])}</button>`).join('')}</div>`;$$('.choice',c.arena).forEach((b,i)=>c.scheduler.listen(b,'click',()=>String(items[i])===String(correct)?c.success():c.failure('Wrong choice')));keyChoices(c)}
function keyChoices(c){c.scheduler.listen(document,'keydown',e=>{const i=+e.key-1,b=$$('.choice',c.arena)[i];if(b)b.click()})}
function pos(c,size=58){const w=Math.max(240,c.arena.clientWidth),h=Math.max(300,c.arena.clientHeight);return [8+c.rng()*Math.max(1,w-size-16),8+c.rng()*Math.max(1,h-size-16)]}
function shuffle(a,r){for(let i=a.length-1;i;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function setupChallenge(id,c){const r=c.rng,L=c.level,A=c.arena,S=c.scheduler;A.innerHTML='';A.className='arena grid';
if(id==='tap-rush'){let n=Math.min(12,4+Math.floor(L/3)),x=0;A.innerHTML=`<button class="big-button">0 / ${n}</button>`;S.listen($('button',A),'click',e=>{e.currentTarget.textContent=`${++x} / ${n}`;if(x===n)c.success()})}
else if(id==='tap-sequence'||id==='reverse'||id==='sort-numbers'){let vals=id==='sort-numbers'?shuffle([2,4,7,9,12,15].slice(0,Math.min(6,3+Math.floor(L/5))),r):Array.from({length:Math.min(8,4+Math.floor(L/5))},(_,i)=>i+1);if(id==='tap-sequence')vals=shuffle(vals,r);if(id==='reverse')vals=shuffle(vals,r);const order=[...vals].sort((a,b)=>id==='reverse'?b-a:a-b);let at=0;A.innerHTML=`<div class="choice-grid">${vals.map(v=>`<button class="choice">${v}</button>`).join('')}</div>`;$$('button',A).forEach(b=>S.listen(b,'click',()=>{if(+b.textContent!==order[at])return c.failure('Wrong order');b.disabled=true;b.style.opacity='.25';if(++at===order.length)c.success()}))}
else if(id==='moving-target'||id==='tiny-target'){A.className='arena';const size=id==='tiny-target'?Math.max(44,68-L):Math.max(48,76-L),b=document.createElement('button');b.className='target';b.style.width=b.style.height=size+'px';b.textContent='●';A.append(b);let [x,y]=pos(c,size),vx=1.3+L*.12,vy=1.1+L*.08;S.raf(()=>{if(id==='moving-target'&&!state.settings.reducedMotion){x+=vx;y+=vy;if(x<4||x>A.clientWidth-size-4)vx*=-1;if(y<4||y>A.clientHeight-size-4)vy*=-1}b.style.transform=`translate(${x}px,${y}px)`});S.listen(b,'click',()=>c.success())}
else if(id==='double-tap'){A.innerHTML='<button class="big-button">TAP ×2</button>';let last=0,n=0;S.listen($('button',A),'click',()=>{const t=performance.now();n=t-last<450?n+1:1;last=t;if(n>=2)c.success()})}
else if(id==='press-hold'){A.innerHTML='<button class="big-button">HOLD<br><small>0%</small></button>';const b=$('button',A);let start=0,down=false;const stop=()=>{if(down)c.failure('Released too soon');down=false};S.listen(b,'pointerdown',e=>{down=true;start=performance.now();if(b.setPointerCapture)b.setPointerCapture(e.pointerId)});S.listen(b,'pointerup',stop);S.listen(b,'pointercancel',stop);S.raf(t=>{if(down){const p=Math.min(100,(t-start)/12);$('small',b).textContent=Math.floor(p)+'%';if(p>=100){down=false;c.success()}}})}
else if(id==='remember-number'){const len=Math.min(8,3+Math.floor(L/4)),v=Array.from({length:len},()=>Math.floor(r()*10)).join('');A.innerHTML=`<div class="memory-value">${v}</div>`;S.timeout(()=>{A.innerHTML='<div class="input-row"><input inputmode="numeric" aria-label="Remembered number" maxlength="8"><button class="btn primary">OK</button></div>';const go=()=>$('input',A).value===v?c.success():c.failure('That was not the number');S.listen($('button',A),'click',go);S.listen($('input',A),'keydown',e=>{if(e.key==='Enter')go()});$('input',A).focus()},Math.max(1400,2600-L*50))}
else if(id==='color-sequence'){const len=Math.min(7,3+Math.floor(L/5)),seq=Array.from({length:len},()=>colors[Math.floor(r()*4)]);A.innerHTML=`<div class="choice-grid">${colors.slice(0,4).map(x=>`<button class="choice color ${x}" aria-label="${x}"></button>`).join('')}</div>`;let show=0,input=-1;const bs=$$('button',A);const flash=()=>{if(show>=len){input=0;return}bs.forEach(b=>b.style.opacity='.3');bs[colors.indexOf(seq[show])].style.opacity='1';S.timeout(()=>{bs.forEach(b=>b.style.opacity='1');show++;S.timeout(flash,220)},450)};flash();bs.forEach((b,i)=>S.listen(b,'click',()=>{if(input<0)return c.failure('Wait for the sequence');if(colors[i]!==seq[input])return c.failure('Wrong color');if(++input===len)c.success()}))}
else if(id==='position-memory'){const total=9,count=Math.min(5,2+Math.floor(L/6)),chosen=shuffle([...Array(total).keys()],r).slice(0,count);A.innerHTML=`<div class="choice-grid" style="grid-template-columns:repeat(3,1fr)">${[...Array(total)].map((_,i)=>`<button class="choice ${chosen.includes(i)?'green':''}" style="aspect-ratio:1" aria-label="Tile ${i+1}"></button>`).join('')}</div>`;S.timeout(()=>{let n=0;const bs=$$('button',A);bs.forEach(b=>b.classList.remove('green'));bs.forEach((b,i)=>S.listen(b,'click',()=>{if(!chosen.includes(i))return c.failure('Wrong tile');if(b.disabled)return;b.disabled=true;b.classList.add('green');if(++n===count)c.success()}))},1800)}
else if(id==='word-memory'){const words=['ORBIT','PIXEL','COMET','NINJA','TURBO','LUNAR','GLITCH','NEON'],word=words[Math.floor(r()*words.length)];A.innerHTML=`<div class="memory-value">${word}</div>`;S.timeout(()=>btnGrid(c,shuffle([...words].filter(x=>x!==word),r).slice(0,3).concat(word).sort(()=>0),word),1600);S.timeout(()=>{if(!$('.choice',A))btnGrid(c,shuffle([...words].filter(x=>x!==word),r).slice(0,3).concat(word),word)},1650)}
else if(id==='flash-count'){let count=3+Math.floor(r()*4),seen=0;A.innerHTML='<div class="memory-value">COUNT</div>';const flash=()=>{if(seen===count)return S.timeout(()=>btnGrid(c,shuffle([count,count+1,count-1,count+2],r),count),500);A.classList.toggle('green');seen++;S.timeout(()=>{A.classList.remove('green');S.timeout(flash,220)},180)};S.timeout(flash,400)}
else if(id==='stop-bar'){A.innerHTML='<div class="bar-track"><div class="bar-zone"></div><div class="bar-cursor"></div></div><button class="btn primary">STOP</button>';let p=0,d=1;S.raf(()=>{p+=d*(1.1+L*.08);if(p>=97||p<=0)d*=-1;$('.bar-cursor',A).style.left=p+'%'});S.listen($('button',A),'click',()=>p>=38&&p<=59?c.success():c.failure('Missed the zone'))}
else if(id==='center-hit'){A.innerHTML='<button class="big-button" style="background:radial-gradient(circle,#fff 0 11%,#ff5577 12% 28%,#fff 29% 46%,#48a7ff 47%)" aria-label="Bullseye"></button>';S.listen($('button',A),'click',e=>{const q=e.currentTarget.getBoundingClientRect(),dx=e.clientX-q.left-q.width/2,dy=e.clientY-q.top-q.height/2;Math.hypot(dx,dy)<q.width*.2?c.success():c.failure('Not close enough to center')})}
else if(id==='smallest'||id==='largest'){const sizes=shuffle([48,64,82,100],r),answer=id==='smallest'?Math.min(...sizes):Math.max(...sizes);A.innerHTML=`<div class="choice-grid">${sizes.map(s=>`<button class="shape" style="width:${s}px;height:${s}px" data-s="${s}" aria-label="Shape size ${s}">◆</button>`).join('')}</div>`;$$('button',A).forEach(b=>S.listen(b,'click',()=>+b.dataset.s===answer?c.success():c.failure(`Not the ${id}`)))}
else if(id==='arithmetic'){const a=2+Math.floor(r()*(8+L)),b=1+Math.floor(r()*9),plus=r()>.35,ans=plus?a+b:a-b;A.innerHTML=`<div><div class="memory-value">${a} ${plus?'+':'−'} ${b}</div><div class="input-row"><input inputmode="numeric" aria-label="Answer"><button class="btn primary">OK</button></div></div>`;const go=()=>+$('input',A).value===ans?c.success():c.failure('Incorrect answer');S.listen($('button',A),'click',go);S.listen($('input',A),'keydown',e=>e.key==='Enter'&&go());$('input',A).focus()}
else if(id==='number-sequence'){const start=1+Math.floor(r()*5),step=2+Math.floor(r()*4),seq=[0,1,2,3].map(i=>start+i*step),ans=start+4*step;A.innerHTML=`<div style="width:100%"><div class="memory-value">${seq.join(' · ')} · ?</div></div>`;S.timeout(()=>btnGrid(c,shuffle([ans,ans+step,ans-1,ans+1],r),ans),500)}
else if(id==='odd-symbol'){const odd=r()>.5?'●':'◆',same=odd==='●'?'◆':'●',n=Math.min(15,8+Math.floor(L/3)),at=Math.floor(r()*n);A.innerHTML=`<div class="choice-grid" style="grid-template-columns:repeat(4,1fr)">${[...Array(n)].map((_,i)=>`<button class="choice" data-ok="${i===at}">${i===at?odd:same}</button>`).join('')}</div>`;$$('button',A).forEach(b=>S.listen(b,'click',()=>b.dataset.ok==='true'?c.success():c.failure('Same symbol')))}
else if(id==='parity'){const n=10+Math.floor(r()*89);A.innerHTML=`<div><div class="memory-value">${n}</div><div class="choice-grid"><button class="choice">ODD</button><button class="choice">EVEN</button></div></div>`;$$('button',A).forEach(b=>S.listen(b,'click',()=>b.textContent===(n%2?'ODD':'EVEN')?c.success():c.failure('Wrong parity')))}
else if(id==='wait-signal'){A.innerHTML='<button class="big-button red">WAIT</button>';const b=$('button',A),delay=900+r()*1800;let ready=false;S.listen(b,'click',()=>ready?c.success():c.failure('Too soon'));S.timeout(()=>{ready=true;b.className='big-button green';b.textContent='TAP!'},delay)}
else if(id==='signal-choice'){const pick=colors[Math.floor(r()*4)];A.innerHTML=`<div><div class="memory-value ${pick}">${pick.toUpperCase()}</div><div class="choice-grid">${shuffle(colors.slice(0,4),r).map(x=>`<button class="choice ${x}">${x}</button>`).join('')}</div></div>`;$$('button',A).forEach(b=>S.listen(b,'click',()=>b.textContent===pick?c.success():c.failure('Wrong signal')))}
else if(id==='falling-catch'){A.className='arena';const b=document.createElement('button');b.className='target';b.style.cssText='width:58px;height:58px';b.textContent='★';A.append(b);let y=-60,x=pos(c,58)[0];S.raf(()=>{y+=1.4+L*.12;b.style.transform=`translate(${x}px,${y}px)`;if(y>A.clientHeight)c.failure('It got away')});S.listen(b,'click',()=>c.success())}
else if(id==='key-flash'){const keys=['A','S','D','F'],k=keys[Math.floor(r()*4)];A.innerHTML=`<div class="memory-value">${k}</div><p>Press the ${k} key</p>`;S.listen(document,'keydown',e=>e.key.toUpperCase()===k?c.success():c.failure('Wrong key'))}
else if(id==='color-change'){A.innerHTML='<button class="big-button blue">WATCH</button>';const b=$('button',A);let changed=false;S.listen(b,'click',()=>changed?c.success():c.failure('Too soon'));S.timeout(()=>{changed=true;b.className='big-button yellow';b.textContent='NOW'},1000+r()*1700)}
else if(id==='except'){const forbidden=r()>.5?'●':'■',vals=shuffle(['●','●','■','■','▲','▲'],r),need=vals.filter(x=>x!==forbidden).length;let got=0;A.innerHTML=`<div><p style="text-align:center">DO NOT TAP <b>${forbidden}</b></p><div class="choice-grid">${vals.map(x=>`<button class="choice">${x}</button>`).join('')}</div></div>`;$$('button',A).forEach(b=>S.listen(b,'click',()=>{if(b.textContent===forbidden)return c.failure('Tapped the forbidden symbol');if(!b.disabled){b.disabled=true;b.style.opacity='.25';if(++got===need)c.success()}}))}
else if(id==='stroop'){const word=colors[Math.floor(r()*4)],ink=colors.filter(x=>x!==word)[Math.floor(r()*3)];A.innerHTML=`<div><div class="memory-value" style="color:${({red:'#ff5577',green:'#63f3d0',blue:'#48a7ff',yellow:'#ffcf4a'})[ink]}">${word.toUpperCase()}</div><div class="choice-grid">${shuffle(colors.slice(0,4),r).map(x=>`<button class="choice">${x.toUpperCase()}</button>`).join('')}</div></div>`;$$('button',A).forEach(b=>S.listen(b,'click',()=>b.textContent.toLowerCase()===ink?c.success():c.failure('Choose the ink color')))}
else if(id==='dont-tap'){A.innerHTML='<button class="big-button red">DO NOT TAP</button>';S.listen($('button',A),'click',()=>c.failure('You tapped it'));S.timeout(()=>c.success(),3000)}
else if(id==='fake-button'){const at=Math.floor(r()*6);A.innerHTML=`<div class="choice-grid">${[...Array(6)].map((_,i)=>`<button class="choice" data-real="${i===at}">${i===at?'REAL':'TAP ME'}</button>`).join('')}</div>`;$$('button',A).forEach(b=>S.listen(b,'click',()=>b.dataset.real==='true'?c.success():c.failure('That button was fake')))}
}
class Game{constructor(mode){this.mode=mode;this.score=0;this.combo=0;this.level=1;this.wins=0;this.coins=0;this.recent=[];this.paused=false;this.ended=false;this.manager=new ChallengeManager(this);this.rng=mode==='daily'?seeded(hash(dateKey())):Math.random;this.dailyOrder=mode==='daily'?shuffle([...challenges].filter(x=>x.minimumLevel<=10),this.rng).slice(0,10):null;this.startAt=performance.now();this.totalPaused=0;this.pauseAt=0}rand(){return this.rng()}start(){this.render();this.next()}render(){screen='game';app.innerHTML=`<section class="screen"><div class="hud"><div class="hud-side"><small>SCORE</small><b id="score">0</b></div><div class="timer" aria-label="Time remaining"><svg viewBox="0 0 86 86"><circle cx="43" cy="43" r="38"></circle><circle class="timer-ring" cx="43" cy="43" r="38"></circle></svg><strong id="time">10.0</strong></div><div class="hud-side"><small>COMBO</small><b id="combo">x0</b></div></div><div class="levelbar"><i id="levelbar"></i></div><div class="top"><small>LEVEL <b id="level">1</b>/20</small><button class="icon" id="pause" aria-label="Pause game">Ⅱ</button></div><div class="challenge-head"><span class="tag" id="cat">READY</span><h2 id="instruction">Get ready…</h2><p id="challengeName"></p></div><div id="arena" class="arena grid"></div></section>`;$('#pause').onclick=()=>this.pause();document.onkeydown=e=>{if(e.key==='Escape')this.paused?this.resume():this.pause()}}
choose(){if(this.mode==='daily')return this.dailyOrder[this.wins];let pool=challenges.filter(x=>x.minimumLevel<=this.level&&!this.recent.includes(x.id));if(!pool.length)pool=challenges.filter(x=>x.minimumLevel<=this.level);return pool[Math.floor(this.rand()*pool.length)]}
next(){if(this.ended)return;if(this.mode==='daily'&&this.wins>=10)return this.finishDaily();const d=this.choose();this.def=d;this.recent.push(d.id);if(this.recent.length>5)this.recent.shift();$('#cat').textContent=d.category.toUpperCase();$('#instruction').textContent=d.instructionGenerator(this);$('#challengeName').textContent=d.name;$('#level').textContent=this.level;$('#levelbar').style.width=(this.level/20*100)+'%';this.duration=d.timeLimit*1000;this.remaining=this.duration;this.tickAt=performance.now();this.manager.start(d);this.timerFrame=requestAnimationFrame(t=>this.tick(t))}
tick(t){if(this.ended||this.paused)return;const dt=t-this.tickAt;this.tickAt=t;this.remaining-=dt;const sec=Math.max(0,this.remaining/1000);$('#time').textContent=sec.toFixed(1);$('.timer-ring').style.strokeDashoffset=239*(1-sec/(this.duration/1000));$('.timer-ring').style.stroke=sec<3?'var(--danger)':'var(--accent)';if(this.remaining<=0)return this.fail('Time ran out');this.timerFrame=requestAnimationFrame(n=>this.tick(n))}
succeed(){if(this.ended||this.locked)return;this.locked=true;cancelAnimationFrame(this.timerFrame);this.manager.cleanup();this.combo++;this.wins++;this.level=Math.min(20,1+Math.floor(this.wins/2));const combo=[0,1,1.2,1.5,2][this.combo]||3,diff=1+(this.level-1)*.06,base=100*this.def.scoreMultiplier,time=Math.floor(this.remaining/1000)*8,points=Math.round((base*diff+time)*combo),coins=Math.max(1,Math.floor(points/100));this.score+=points;this.coins+=coins;state.successes++;state.highestCombo=Math.max(state.highestCombo,this.combo);state.highestLevel=Math.max(state.highestLevel,this.level);state.categories[this.def.category]=(state.categories[this.def.category]||0)+1;state.challengeWins[this.def.id]=(state.challengeWins[this.def.id]||0)+1;$('#score').textContent=this.score;$('#combo').textContent='x'+this.combo;beep(true);buzz(25);const note=document.createElement('div');note.className='toast';note.innerHTML=`<b>+${points} points · ◆ ${coins}</b><span>(${Math.round(base)} base × ${diff.toFixed(2)} level + ${time} time) × ${combo} combo</span>`;document.body.append(note);announce.textContent=`Success. ${points} points`;setTimeout(()=>{note.remove();this.locked=false;this.next()},750)}
fail(reason){if(this.ended||this.locked)return;this.ended=true;cancelAnimationFrame(this.timerFrame);this.manager.cleanup();beep(false);buzz([70,40,70]);this.complete(reason)}
finishDaily(){this.ended=true;this.manager.cleanup();state.daily={date:dateKey(),complete:true,best:Math.max(state.daily.date===dateKey()?state.daily.best:0,this.score)};this.complete('Daily sequence complete!')}
complete(reason){document.onkeydown=null;const elapsed=Math.max(0,Math.round((performance.now()-this.startAt-this.totalPaused)/1000));state.runs++;state.failures+=reason==='Daily sequence complete!'?0:1;state.bestScore=Math.max(state.bestScore,this.score);state.totalScore+=this.score;state.coins+=this.coins;state.totalCoins+=this.coins;state.totalTime+=elapsed;if(this.mode==='daily'&&state.daily.date!==dateKey())state.daily={date:dateKey(),complete:false,best:0};if(this.mode==='daily')state.daily.best=Math.max(state.daily.best,this.score);const fresh=checkAchievements();save();screen='over';app.innerHTML=`<section class="screen gameover"><div class="kicker">${esc(reason)}</div><h1>${this.mode==='daily'?'DAILY RESULT':'RUN OVER'}</h1><div class="score">${this.score}</div><p class="reward">◆ ${this.coins} coins · Level ${this.level} · Best combo x${this.combo}</p>${fresh.length?`<div class="card">Achievement unlocked: <b>${fresh.map(esc).join(', ')}</b></div>`:''}<div class="actions"><button class="btn primary" id="again">PLAY AGAIN</button><button class="btn" data-go="menu">MAIN MENU</button></div></section>`;$('#again').onclick=()=>startGame(this.mode);bindNav()}
pause(){if(this.paused||this.ended||this.locked)return;this.paused=true;this.pauseAt=performance.now();cancelAnimationFrame(this.timerFrame);this.manager.pause();const p=document.createElement('div');p.className='pause';p.innerHTML='<div class="card"><div class="kicker">TIME FROZEN</div><h1>Paused</h1><div class="actions"><button class="btn primary" id="resume">RESUME</button><button class="btn" id="restart">RESTART</button><button class="btn ghost" id="quit">MAIN MENU</button></div></div>';document.body.append(p);$('#resume').onclick=()=>this.resume();$('#restart').onclick=()=>{p.remove();this.destroy();startGame(this.mode)};$('#quit').onclick=()=>{p.remove();this.destroy();renderMenu()}}
resume(){if(!this.paused)return;this.totalPaused+=performance.now()-this.pauseAt;this.paused=false;$('.pause')?.remove();this.manager.resume();this.tickAt=performance.now();this.timerFrame=requestAnimationFrame(t=>this.tick(t))}
destroy(){this.ended=true;cancelAnimationFrame(this.timerFrame);this.manager.cleanup();document.onkeydown=null;$('.pause')?.remove()}}
function startGame(mode){game&&game.destroy();game=new Game(mode);game.start()}
applyCosmetic();checkAchievements();renderMenu();
})();